# Generated by Django 3.2.10 on 2022-06-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20220607_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaclone.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaclone.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaclone.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaclone.profile')),
            ],
        ),
    ]
