# Generated by Django 3.2.10 on 2022-06-09 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
